# Generated by Django 5.2.7 on 2025-10-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist", models.CharField()),
                ("amp", models.CharField()),
                ("amp_url", models.URLField()),
                ("guitar", models.CharField()),
                ("guitar_url", models.URLField()),
                ("pedal", models.CharField()),
                ("pedal_url", models.URLField()),
                ("views", models.IntegerField(default=0)),
            ],
        ),
    ]
